# Generated by Django 5.1.2 on 2024-10-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_count', models.IntegerField(default=0, verbose_name='happy Clients')),
                ('projects', models.IntegerField(default=0, verbose_name='Projects')),
                ('hours_support', models.IntegerField(default=0, verbose_name='Hours of Support')),
                ('awards', models.IntegerField(default=0, verbose_name='Awards')),
            ],
        ),
    ]
