# Generated by Django 5.1.2 on 2024-10-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='awards',
            field=models.IntegerField(default=1, verbose_name='Awards'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='clients_count',
            field=models.IntegerField(default=1, verbose_name='happy Clients'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='hours_support',
            field=models.IntegerField(default=1, verbose_name='Hours of Support'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='projects',
            field=models.IntegerField(default=1, verbose_name='Projects'),
        ),
    ]
