# Generated by Django 5.1.2 on 2024-10-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_stats_awards_alter_stats_clients_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
    ]
