# Generated by Django 5.1.2 on 2024-10-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(verbose_name='About Heading')),
                ('title', models.CharField(max_length=200, verbose_name='About Title')),
                ('description', models.TextField(verbose_name='About Description')),
                ('image', models.ImageField(upload_to='about/', verbose_name='About Image')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('website', models.URLField()),
                ('phone_number', models.BigIntegerField(default=0)),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('Freelance', models.BooleanField(default=False, verbose_name='Freelancing')),
            ],
        ),
    ]
