# Generated by Django 5.1.2 on 2024-10-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Freelance',
            field=models.BooleanField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='Inactive', verbose_name='Freelancing'),
        ),
    ]
