# Generated by Django 5.1.2 on 2024-10-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_freelance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Freelance',
            field=models.BooleanField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='active', max_length=20, verbose_name='Freelancing'),
        ),
    ]
