# Generated by Django 5.1.2 on 2024-10-26 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('education', 'Education'), ('experience', 'Professional Experience'), ('certification', 'Certification')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Position or Degree Title')),
                ('institution_name', models.CharField(max_length=200, verbose_name='Institution or Company')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='resume.resumesection')),
            ],
        ),
    ]
