# Generated by Django 5.1.2 on 2024-10-25 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilldata',
            name='skills',
        ),
        migrations.AddField(
            model_name='skilldata',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skilldata', to='skill.skill'),
        ),
    ]
